# Generated by Django 4.2.7 on 2023-11-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('nome_coordenador', models.CharField(max_length=100)),
                ('nome_professor', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('carga_horaria_curso', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('localizacao', models.CharField(max_length=100)),
            ],
        ),
    ]
